// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/dc0d/workshop/interface_adapters/web/api"
)

// Injectors from wire_injectors.go:

func injectStatementHandler() *api.StatementHandler {
	statementViewRepository := provideStatementViewRepository()
	bankStatement := provideBankStatement(statementViewRepository)
	statementHandler := api.NewStatementHandler(bankStatement)
	return statementHandler
}

func injectTransactionCommandHandler() *api.TransactionCommandHandler {
	accountRepository := provideAccountRepository()
	handleTransaction := provideHandleTransaction(accountRepository)
	transactionCommandHandler := api.NewTransactionCommandHandler(handleTransaction)
	return transactionCommandHandler
}
