// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repositories_test

import (
	"gitlab.com/dc0d/go-workshop/interface_adapters/repositories"
	"gitlab.com/dc0d/go-workshop/model"
	"sync"
)

var (
	lockStatementViewStorageReadMockFind sync.RWMutex
)

// Ensure, that StatementViewStorageReadMock does implement repositories.StatementViewStorageRead.
// If this is not the case, regenerate this file with moq.
var _ repositories.StatementViewStorageRead = &StatementViewStorageReadMock{}

// StatementViewStorageReadMock is a mock implementation of repositories.StatementViewStorageRead.
//
//     func TestSomethingThatUsesStatementViewStorageRead(t *testing.T) {
//
//         // make and configure a mocked repositories.StatementViewStorageRead
//         mockedStatementViewStorageRead := &StatementViewStorageReadMock{
//             FindFunc: func(id string) (*model.Statement, error) {
// 	               panic("mock out the Find method")
//             },
//         }
//
//         // use mockedStatementViewStorageRead in code that requires repositories.StatementViewStorageRead
//         // and then make assertions.
//
//     }
type StatementViewStorageReadMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(id string) (*model.Statement, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// ID is the id argument value.
			ID string
		}
	}
}

// Find calls FindFunc.
func (mock *StatementViewStorageReadMock) Find(id string) (*model.Statement, error) {
	if mock.FindFunc == nil {
		panic("StatementViewStorageReadMock.FindFunc: method is nil but StatementViewStorageRead.Find was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockStatementViewStorageReadMockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	lockStatementViewStorageReadMockFind.Unlock()
	return mock.FindFunc(id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//     len(mockedStatementViewStorageRead.FindCalls())
func (mock *StatementViewStorageReadMock) FindCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockStatementViewStorageReadMockFind.RLock()
	calls = mock.calls.Find
	lockStatementViewStorageReadMockFind.RUnlock()
	return calls
}
